### ISSUE TITLE
vhdl_make_build_system

### ISSUE THREAD

**Issue by nathankp** [RPeschke/SCROD_ETHERNET_V3#6]
I am following README Instructions to build the Example project. When running vhdl_make_build_system.py in bash, I get the following error:
`Traceback (most recent call last):
  File "vhdl_make_build_system.py", line 52, in <module>
    with open(args.path+"/vhdl_build_setup.xml","w",newline="") as f:
TypeError: 'newline' is an invalid keyword argument for this function`

**Comment by RPeschke** [comment]
i am almost sure you are using python 2.x which is not supported 

just run the same file with python3 and let me know what happened

**Comment by nathankp** [comment]
Thanks that solved that error I will add to readme that they must use python3. Another error came up though: 
`Traceback (most recent call last):
  File "vhdl_make_build_system.py", line 52, in <module>
    with open(args.path+"/vhdl_build_setup.xml","w",newline="") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/vhdl_build_setup.xml'
`
wondering if there was another script I was supposed to run before this one?

**Comment by nathankp** [comment]
I figured out, the build directory was not in the same directory as the vhdl_build_system, I found it in the main directory of the SCROD_ETHERNET_V3, and moved it into vhdl_build_system.
